name: Update Repo

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
  workflow_dispatch:
  
jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Delete old files
        continue-on-error: true
        run: rm Packages Packages.gz Packages.bz2 Release

      - name: Create Packages file
        run: apt-ftparchive packages ./debs > Packages
        
      - name: Zip Packages file to .gz and .bz2
        run: |
          gzip -c9 Packages > Packages.gz
          bzip2 -c9 Packages > Packages.bz2
          
      - name: Create Releases file
        run: apt-ftparchive release -c ./repo.conf . > Release
        
      - name: Set Git username
        run: |
          git config --global user.name "GitHub Actions"
        
      - name: Stage, commit and push files
        run: |
          git add .
          git commit -m "Updated Repo"
          git push origin
